server:
  port: 9001
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/itemstaffmanage?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
#    username: root
#    password: 123


  jpa:
      database: mysql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect