server:
  port: 9001
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/itemstaffmanage?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
#    username: root
#    password: 123

  mail:
      host: smtp.*****.com
      username: ******@sina.com
      password: ********
      nick: *******
      properties:
        mail:
          debug: true
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
  jpa:
      database: mysql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
qiniu:
  accessKey: 4******Q
  secretKey: EY9l******JM_8P3s
  bucketUrl: http://sm********loud.net
  bucketName: smar******mpus
  privateBucketUrl: http://camp******cloud.net
  privateBucketName: smar******vate
  expires: 43200
