server:
  port: 9001
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/itemstaffmanage?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
#    username: root
#    password: 123

  mail:
      host: smtp.*****.com
      username: ******@sina.com
      password: ********
      nick: *******
      properties:
        mail:
          debug: true
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
  jpa:
      database: mysql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
qiniu:
  accessKey: 4GY_U6vPAypr6zc4DkwdpYpNFK2RilZwLo-_sAjQ
  secretKey: EY9lMY6xTnMPndGWPrgoxTNgs3uh9YktPJM_8P3s
  bucketUrl: http://smartcampus.eduincloud.net
  bucketName: smartcampus
  privateBucketUrl: http://campuspri.eduincloud.net
  privateBucketName: smartcampus-private
  expires: 43200